---
ntpServer: "0.asia.pool.ntp.org"
ceph_user: "ceph"
controller: "control"
compute: "compute01"
ntp_check: "1"
cluster: "ceph"
journal_size: 1024
pool_size: 2
min_size: 1
mon_clock_drift_allowed: 1
mon_clock_drift_warn_backoff: 30
openstack_glance_pool: "images"
openstack_cinder_pool: "volumes"
openstack_nova_pool: "vms"
openstack_cinder_backup_pool: "backup"
pg_num: 32
image_auth: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=images'"
volumes_auth: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rwx pool=images, allow rwx pool=vms'"
#nova_auth: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=vms'"
backup_auth: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=backup'"
ceph_conf: "/etc/ceph/ceph.conf"
ceph_path: "/etc/ceph/"
ceph_home: "/home/ceph/"
root_password: "@dmin123"
ceph_image: "/etc/ceph/ceph.client.images.keyring"
ceph_volumes: "/etc/ceph/ceph.client.volumes.keyring"
ceph_nova: "/etc/ceph/ceph.client.nova.keyring"
ceph_backup: "/etc/ceph/ceph.client.backup.keyring"